[package]
name = "rustoban"
version = "0.1.0"
edition = "2021"
authors = ["Mirko Förster <mfoerster.hb@proton.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.8.1"
